### ISSUE TITLE
Emergency programs are ignored

### ISSUE THREAD

**Issue by meafs** [sustcast/sustcast-core-v0#31]

**Comment by seekermind** [comment]
Emergency programs are not actually ignored. The problem is in  `downloadOgg()` function. As pydub is used to convert every track to `.ogg` format, in case of a big file, ram gets overwhelmed. As a result, the program exits with a notice `killed`.

Devs should avoid converting big audio files with pydub (which I think uses ffmpeg to do the job) instead an already converted file can be placed in `program_schedule.csv` or `emergency_programs`.
After that, replacing the following line with `copyfile(file_path, Constant.default_ogg_download_path)`  should solve the problem.

https://github.com/sustcast/sustcast-core-v0/blob/2545a554791db7c1f69e1fb36bb6a996a8cb931f/core/SongDownload.py#L51

**Comment by meafs** [comment]
Thanks a lot for the contribution Vai ❤️

**Comment by meafs** [comment]
Also, you helped me to fix the timezone issue. We really appreciate your contribution to SUSTCast :)
